version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: spring_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spring
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

volumes:
  db_data:
